# Generated by Django 2.1.5 on 2019-01-24 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
